### ISSUE TITLE
Development for an inventory listing

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#10]
## Feature description

As a developer I need to implement the aforementioned storyboard using the platform dependent inventory components as a basis.

## Acceptance Criteria

- [x] RHSM API, and state management set up, #360 #381 #382 #384
    - [x] System table , #312
    - [x] Guests, #330 #343 
- [x] Toolbar filters added, RHSM API and base queries/filters set up #372 #377 
   - [x] usage dropdown filters, #361 #368 #377 
   - [x] paging for header and footer #372 
- [x] Base inventory, and PF table component activated #372  #390 
   - [x] table components activated, #346 #350 #371 
   - [x] hosts inventory displayed #372 
   - [x] guests inventory displayed #390 
-  ~System detail if available, inventory API connected~ Follow up story/issues
   - ascending/desc column sorting

## Assumptions and Questions
- RHSM based api will be used for the initial inventory display
- example implementations, [vulnerabilities](https://github.com/RedHatInsights/vulnerability-ui)
- platform component needed?
   - host based inventory
      - because inventory components appear to bake the toolbar into the header of the table we may have to use the PF components directly
- table style - phase 1
   - compact table
   - no row select
   - filter header will be above graph
      - add paging
      - add usage filter, https://github.com/RedHatInsights/rhsm-subscriptions/blob/master/src/main/java/org/candlepin/subscriptions/db/model/Usage.java#L37-L39
         - "Not specified"
         - "Production"
         - "Development/Test"
         - "Disaster Recovery"
   - paging should also be at bottom to align with platform
- ~current understanding is ... this is unfiltered~
      - ~do we need sorting, filtering, paging? big question about pagination~
      - ~does the date selection in the potential 30 day dropdown update this listing?~

- Relates to #8 

#### Latest design as of 202007
![image (1)](https://user-images.githubusercontent.com/3761375/89443049-bb065800-d71d-11ea-9a13-ac27174f7131.png)

#### Prior designs
![Screen Shot 2020-06-26 at 4 42 25 PM](https://user-images.githubusercontent.com/3761375/85899464-1c0c4900-b7cc-11ea-85b1-9d669f1d0f80.png)

![Screen Shot 2020-06-26 at 4 50 28 PM](https://user-images.githubusercontent.com/3761375/85901822-9b9c1700-b7d0-11ea-8c68-86fac2d1b688.png)

![Screen Shot 2020-06-26 at 4 44 29 PM](https://user-images.githubusercontent.com/3761375/85899719-7c02ef80-b7cc-11ea-9b63-eb7236d80118.png)

@bclarhk

**Comment by ntkathole** [comment]
@cdcabrera another issue (other than mentioned in https://github.com/RedHatInsights/curiosity-frontend/pull/372#issuecomment-672631760) I see is of pagination. Default selected pagination count is 10 while inventory list 5 hosts.

![Screenshot from 2020-08-19 10-32-37](https://user-images.githubusercontent.com/16951913/90594342-d38b6d80-e207-11ea-9d99-f0ff4091b37c.png)
