### ISSUE TITLE
Implement null data points NOT being a dip down to zero

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#180]
## Description
As a user I would like to be able to note areas of "made up" data visually with either some type of cross-hatching display or faded gray area of the chart.

As a developer I recognize the difference between data failures and non-existent data, and would like to see non-existent data denoted as charting gaps instead of displaying as zero.

## Acceptance Criteria
- [x] Implement tooltips that reflect a "[some product]: no data" instead of a singular "No data" tooltip
- [ ] Create story for implementing design to denote null data vs 0 data points from issue #166 
- [ ] Create tracking story for API changes

## Assumptions and Questions
- API tracking https://projects.engineering.redhat.com/browse/ENT-1964
-  we can confirm our charting tools handle `null` vs `0` displays see research story/issue #166 

![Screen Shot 2020-02-25 at 9 28 41 AM](https://user-images.githubusercontent.com/3761375/75256336-51b70c00-57b1-11ea-9ea8-c741796d0a9d.png)

**Comment by cdcabrera** [comment]
As of 20200317 the decision is to handle this at the API level.
