### ISSUE TITLE
Prep build config and copy work for the move from prod-beta to prod-stable

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#218]
## Description
As a developer and designer I need to confirm that we are prepped for the move to production.

**Must have roll out checklist**
- [x] [Dev, confirm the beta path used in the package.json NPM script for proxy run doesn't need to be updated](https://github.com/RedHatInsights/curiosity-frontend/blob/master/package.json#L67) - Reason, we're still using beta as the developer test bed for new features. When the QA environment becomes full fledged we can revisit this by possibly aiming for the stable environments.
- [x] [Dev, confirm routing test checks](https://github.com/RedHatInsights/curiosity-frontend/blob/master/src/components/router/__tests__/routerHelpers.test.js#L12), see #222 
   - [x] [Dev, confirm dynamic routing handles path change](https://github.com/RedHatInsights/curiosity-frontend/blob/master/src/components/router/routerHelpers.js#L13)
- [x] [Dev, proxy configs updated](https://github.com/RedHatInsights/curiosity-frontend/blob/master/config/spandx.config.js), see #222 
- [x] [Dev, prod and beta GUI build configs updated](https://github.com/RedHatInsights/curiosity-frontend/blob/master/.travis/custom_release.sh#L24), see #222
- [x] [Dev, prod and beta GUI CI and QA scripts updated](https://github.com/RedHatInsights/curiosity-frontend/blob/master/.travis/custom_release.sh#L6) see #222
- [x] Dev, minimum git branches updated to reflect new breakout of... see #222
   - master = `prod-stable`
   - ci-beta = `ci-beta` (alternatives include calling this `ci` or `dev`, this can be done post)
   - ci-stable = `ci-stable` (alternatives include calling this `qa` or `test`, this can be done post)
   - stage = `prod-beta`
- [x] Dev, `CONTRIBUTING.md` should be updated to reflect new GUI branch process, see #222
- [x] [Dev, platform config PR setup](https://github.com/RedHatInsights/cloud-services-config) and fully merged into stable
   - [x] PR merged into "ci-stable" environment branch
   - [x] PR merged into "qa-stable" environment branch
   - [x] PR merged into "prod-stable" environment branch
- [x] UI/UX, Pendo path references updated
   - Crosses all environments
- [x] UI/UX, CCS, OptIn/Tour view dev and copy wording, see below screenshot
   - ~Confirm icon needs, or doesn't need, to be updated to match platform.~
      - The "opt-in" view is replacing this view
   - [x] [Dev locale copy configs updated](https://github.com/RedHatInsights/curiosity-frontend/blob/master/public/locales/en-US.json#L28-L34)
- [x] Confirm CCS ~has updated~ is planning related documentation paths
   - CCS is aiming for the 23rd as a release, marking this a "date note" only
- [x] Confirm the platform landing page card for Subscription Watch is live

**Nice to haves**
- Dev, prod and beta environments running parallel, utilized as a form of feature testing and QE interaction

**Assumptions and Questions**
- Consideration for maintaining both beta and prod environments to demo beta features. At minimum we may be able to perform this at the GUI level
- Pendo handling multiple environments
- Prep build config work for utilizing the prod and beta paths as a form of separating environments. This should correlate with any planned move by management to request the production path be updated
- Relates to #144 #179 #186

#### New OptIn View
(Tour icon/graphic to be updated accordingly)
![Screen Shot 2020-04-14 at 2 09 24 PM](https://user-images.githubusercontent.com/3761375/79258810-b578bf80-7e59-11ea-8825-c533c596d03b.png)

![Screen Shot 2020-04-14 at 2 09 36 PM](https://user-images.githubusercontent.com/3761375/79258819-b90c4680-7e59-11ea-92ee-0f583ebc2916.png)

#### Old Tour View copy
**No longer used**
![Screen Shot 2020-03-12 at 11 50 12 AM](https://user-images.githubusercontent.com/3761375/76539913-cc418600-6457-11ea-90dd-1314fc9f1c4f.png)

@rblackbu

**Comment by rblackbu** [comment]
ack, verified and looks good, thanks

**Comment by cdcabrera** [comment]
Tasks completed as of 20200420
