### ISSUE TITLE
Review and implement using API opt-in error code

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#260]
## Description
As a developer I should review the need for using the RHSM API error code associated with opt-in, in addition to the http status of `403`

## Acceptance Criteria
- [x] Confirmed RHSM error code `SUBSCRIPTIONS1004`
- [x] Implemented use of `403` vs ~`SUBSCRIPTIONS1003`~ `SUBSCRIPTIONS1004` vs the **opt-in** endpoint `get` 
response on Curiosity
- ~Updated the Insights Dashboard card~ see #281 
   - [x] Confirm this is needed, date, and then separate task, see proposed change here https://github.com/cdcabrera/insights-dashboard/commit/676d5ff8b66d82e08bb24ce6e60e964d66d5e0b9
- [x] confirm, RBAC related permissions, if available, are coming through via global platform method

## Assumptions and Questions
- Current use of the `403` status is used across both Curiosity and the Insights Dashboard
- An alternative to the error code is using the opt-in `get` to confirm the user is "opted in"
- Relates https://github.com/RedHatInsights/rhsm-subscriptions/pull/133
- Relates to #256

```
{
  "errors": [
    {
      "status": "string",
      "code": "SUBSCRIPTIONS1003",
      "title": "string",
      "detail": "string"
    }
  ]
}
```

from ... https://github.com/RedHatInsights/rhsm-subscriptions/blob/5080abd485015029179b4d4284834eec34f247d9/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java#L53
