### ISSUE TITLE
Subscription Watch card updates for Insights Dashboard part 2

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#266]
## Description
As a developer and designer I need to address UI/UX behavior of the Subscriptions Utilized card on Dashboard

## Acceptance Criteria
- [x] tooltip hover area expanded
- [x] links from products to products under Subscription Watch implemented
- [x] fallback "no data" display implemented

## Assumptions and Questions
- Fallback state for "no data" https://github.com/RedHatInsights/insights-dashboard/issues/96
- Tooltips need to be expanded https://github.com/RedHatInsights/insights-dashboard/issues/122
- Links from product labels need to redirect towards Subs Watch https://github.com/RedHatInsights/insights-dashboard/issues/130
