### ISSUE TITLE
Expose Ansible product id(s) through a view

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#297]
## Description
As a developer I need to activate the product IDs associated with Ansible.

## Acceptance Criteria
- [ ] platform left navigation update
- [ ] Ansible related view(s) added
   - [ ] what data facets and legend items to display
      - include "plain word" descriptions

## Assumptions and Questions
- per API team a few of the IDs are within numeric form
- https://github.com/RedHatInsights/rhsm-subscriptions/blob/master/src/main/resources/product_id_to_products_map.yaml#L48-L52
- A UX/UI session is most likely needed to refine what is expected
- Consult product owner for data facets

**Comment by cdcabrera** [comment]
Multiple reorgs on directory structure have taken place since this time. As of 202212 reevaluated, reopen as necessary on the appropriate board.
