### ISSUE TITLE
Connect Graph API

### ISSUE THREAD

**Issue by cdcabrera** [RedHatInsights/curiosity-frontend#9]
## Feature description

As a developer I'd like to view actual data associated with the dashboard graph.

### Assumptions and Questions
- API response schema should match proposed mocks
  - confirm authentication header formats for interacting with the API
  - confirm parameters
  - confirm response properties

## Acceptance Criteria
- [x] Initial base redux layout, tests against mock data laid out
- [x] Verify that the appropriate headers are being set
  - authorization/tokens
  - environment, if required
- [x] Verify query parameters are available, and can be accessed through Redux
- [x] Verify that responses are being consumed through the Redux state management layer
  - If available, also verify that the responses match proposed examples within proposed OpenApi spec
- [x] Verify service and Redux unit tests have been updated

### Phase 1 work
* Phase 1 should include connecting to the RHSM API. This story assumes a spec/examples/mocks being minimally available for display consumption
#### Cloud Meter
Cloud Meter's api will not be consumed during phase 1
* Reference [cloudigrade for report params and commands](https://gitlab.com/cloudigrade/cloudigrade/blob/master/docs/rest-api-examples.rst)
* Reference [cloudigrade, accessing the APIs](https://gitlab.com/cloudigrade/cloudigrade/wikis/how-do-i-reach-these-apis)
